#!/usr/bin/env bash

if [ "$#" -ne 4 ]; then
        echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

if [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
