#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure firewall to allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create directory for web content
sudo mkdir -p /var/www/html

# Set appropriate permissions
sudo chmod -R 755 /var/www

# Create an index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.nerdsquad.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
