#!/usr/bin/env bash
# Displays content of the current directory in a list format Where only the part of the name after the first dash is displayed
content=$(ls -1)
for file in $content
do
	echo "${file#*-}"
done
